In [15]:
#Numpy

In [9]:
import numpy as np

In [10]:
arreglo = np.array([0,1,2,3,4,5])

In [11]:
arreglo, type(arreglo)

(array([0, 1, 2, 3, 4, 5]), numpy.ndarray)

In [12]:
notas = [16,17,14,17,19,15]
ar_notas = np.array(notas, dtype=float)

In [13]:
ar_notas, type(ar_notas[0])

(array([16., 17., 14., 17., 19., 15.]), numpy.float64)

In [14]:
ar_notas_todas = np.array(([0,1,2,3,4,5], notas))
ar_notas_todas

array([[ 0,  1,  2,  3,  4,  5],
       [16, 17, 14, 17, 19, 15]])

In [16]:
#ndim

In [17]:
print(ar_notas_todas.ndim)
print(ar_notas.ndim)

2
1


In [18]:
#shape

In [19]:
print(ar_notas_todas.shape)
print(ar_notas.shape)

(2, 6)
(6,)


In [20]:
#Arrays especiales

In [21]:
arr = np.zeros((2,3), dtype=float)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
ar2 = np.ones((3,4), dtype=float)
print(ar2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
ar4 = np.identity((4), dtype=float)
print(ar4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
ar5 = np.arange(1,9)
print(ar5)


[1 2 3 4 5 6 7 8]
