In [1]:
#Producto de arrays

In [2]:
import numpy as np

a = np.array([1,2,3], float)
b = np.array([0,1,1], float)

np.dot(b, a)

5.0

In [3]:
a.dot(b)

5.0

In [4]:
#Productos de matrices

In [5]:
a = np.array([[5, 2], [4, 8]], float)
b = np.array([[2, 4], [5, 3]], float)

print(a, "\n ---------------")
print(b, "\n ---------------")

[[5. 2.]
 [4. 8.]] 
 ---------------
[[2. 4.]
 [5. 3.]] 
 ---------------


In [6]:
np.dot(a, b)

array([[20., 26.],
       [48., 40.]])

In [7]:
a @ b

array([[20., 26.],
       [48., 40.]])

In [8]:
a = np.array([[0, 1, 4], [5, 2, 3], [1, 4, 8]], float)
b = np.array([2, 3, 5], float)

print(a, "\n ---------------")
print(b, "\n ---------------")

[[0. 1. 4.]
 [5. 2. 3.]
 [1. 4. 8.]] 
 ---------------
[2. 3. 5.] 
 ---------------


In [9]:
np.dot(a, b)

array([23., 31., 54.])

In [10]:
a @ b 

array([23., 31., 54.])

In [11]:
print(np.matmul(a, b))

[23. 31. 54.]


In [12]:
#Determinante de una matriz

In [13]:
a = np.array([[8, 5], [3, 4]])

print(a, "\n ---------------")

np.linalg.det(a)

[[8 5]
 [3 4]] 
 ---------------


17.0

In [14]:
#Auto-valores y auto-vectores

In [15]:
vals, vecs = np.linalg.eig(a)

print(vals, "\n ---------------")
print(vecs, "\n ---------------")

[10.35889894  1.64110106] 
 ---------------
[[ 0.90440309 -0.61810602]
 [ 0.4266791   0.78609474]] 
 ---------------
