In [1]:
import numpy as np

arr = np.array([5,36,17,18,9])

arr_2 = np.array([8,24,17,19,9])

In [2]:
np.add(arr, arr_2)

array([13, 60, 34, 37, 18])

In [3]:
np.subtract(arr,arr_2)

array([-3, 12,  0, -1,  0])

In [4]:
np.multiply(arr,arr_2)

array([ 40, 864, 289, 342,  81])

In [5]:
np.divide(arr,arr_2)

array([0.625     , 1.5       , 1.        , 0.94736842, 1.        ])

In [6]:
np.array_equal(arr,arr_2)

False

In [7]:
np.fmin(arr,arr_2)

array([ 5, 24, 17, 18,  9])

In [8]:
np.fmax(arr,arr_2)

array([ 8, 36, 17, 19,  9])