In [1]:
import numpy as np

arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [2]:
arr_flot = np.random.rand(4,1)
arr_flot

array([[0.40728171],
       [0.71978163],
       [0.76406153],
       [0.94129548]])

In [3]:
arr_ent = np.random.randint(100, size=(2,3))
arr_ent

array([[53,  6, 14],
       [29, 22, 89]])

In [4]:
arr_6 = np.full((3,3),6)
arr_6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [5]:
np.append(arr, [12,13,14,51])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 12, 13, 14, 51])

In [6]:
np.insert(arr,2, [42,34])

array([ 0,  2, 42, 34,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.delete(arr_ent,1,axis=0)

array([[53,  6, 14]])

In [8]:
np.delete(arr_ent,0,axis=1)

array([[ 6, 14],
       [22, 89]])