In [1]:
#As type

In [2]:
import numpy as np

arr_ent = np.random.randint(100, size=(3,4))
arr_ent

array([[45, 65, 34, 37],
       [20, 38, 74, 11],
       [65, 27, 28, 58]])

In [3]:
arr_ent.astype(float)

array([[45., 65., 34., 37.],
       [20., 38., 74., 11.],
       [65., 27., 28., 58.]])

In [4]:
#Sort

In [5]:
arr_ent

array([[45, 65, 34, 37],
       [20, 38, 74, 11],
       [65, 27, 28, 58]])

In [6]:
arr_ent.sort()
arr_ent

array([[34, 37, 45, 65],
       [11, 20, 38, 74],
       [27, 28, 58, 65]])

In [7]:
arr_ent.sort(axis=0)
arr_ent

array([[11, 20, 38, 65],
       [27, 28, 45, 65],
       [34, 37, 58, 74]])

In [8]:
#Reshape

In [9]:
arr_ent

array([[11, 20, 38, 65],
       [27, 28, 45, 65],
       [34, 37, 58, 74]])

In [10]:
arr_ent = arr_ent.reshape(4,3)
arr_ent

array([[11, 20, 38],
       [65, 27, 28],
       [45, 65, 34],
       [37, 58, 74]])

In [11]:
#Flatten

In [12]:
plano_arr = arr_ent.flatten()

print(arr_ent)
print(plano_arr)

[[11 20 38]
 [65 27 28]
 [45 65 34]
 [37 58 74]]
[11 20 38 65 27 28 45 65 34 37 58 74]


In [13]:
#To list

In [14]:
lista_arr = plano_arr.tolist()
lista_arr
type(lista_arr)

list

In [15]:
#Separar y juntar arrays

In [16]:
arrays= np.split(arr_ent, 4)
arrays

[array([[11, 20, 38]]),
 array([[65, 27, 28]]),
 array([[45, 65, 34]]),
 array([[37, 58, 74]])]

In [17]:
np.concatenate((arrays[1],arrays[0]),axis=0)

array([[65, 27, 28],
       [11, 20, 38]])

In [18]:
#La matriz transpuesta

In [19]:
arr_ent

array([[11, 20, 38],
       [65, 27, 28],
       [45, 65, 34],
       [37, 58, 74]])